import { useEffect, useState } from 'react';
import { dataService } from '../services/dataService';

export default function CareerPath() {
  const [careerPathData, setCareerPathData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    dataService.getCareerPath()
      .then(res => setCareerPathData(res.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return (
    <div className="flex flex-col items-center justify-center p-20 gap-4 text-indigo-600 animate-pulse">
      <svg className="animate-spin h-8 w-8 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
      <span className="font-bold text-lg tracking-wide">Querying Inference Models...</span>
    </div>
  );

  return (
    <div className="max-w-5xl">
      <div className="mb-10">
        <h1 className="text-4xl font-black text-slate-900 tracking-tight">AI Trajectory Mapping</h1>
        <p className="text-slate-500 mt-2 text-lg">Predictive career modeling generated by parsing your demographic and experiential vectors.</p>
      </div>

      {!careerPathData ? (
        <div className="p-10 border border-slate-200 bg-white rounded-2xl shadow-sm flex flex-col items-center text-center">
          <div className="h-16 w-16 bg-rose-100 text-rose-600 rounded-full flex items-center justify-center mb-4 border-4 border-white shadow-sm">
             <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
             </svg>
          </div>
          <h2 className="text-xl font-bold text-slate-800 mb-2">Insufficient Graph Density</h2>
          <p className="text-slate-500 max-w-lg mb-6 leading-relaxed">Ensure your profile metadata (Skills, Education, Experience) is fully populated. The generative ML core requires dense relationship graphs to formulate accurate predictions.</p>
          <button className="bg-slate-900 hover:bg-indigo-600 text-white font-bold py-2.5 px-6 rounded-lg transition-colors shadow-sm focus:ring-2 focus:ring-slate-900 focus:ring-offset-2">
            Return to Profile
          </button>
        </div>
      ) : (
        <div className="relative overflow-hidden bg-white border border-slate-200 p-8 sm:p-12 rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
          {/* Abstract Generative Background Elements */}
          <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-br from-indigo-100/50 to-fuchsia-100/50 blur-3xl -translate-y-1/2 translate-x-1/2 rounded-full pointer-events-none"></div>
          <div className="absolute bottom-0 left-0 w-72 h-72 bg-gradient-to-tr from-emerald-100/40 to-cyan-100/40 blur-3xl translate-y-1/2 -translate-x-1/2 rounded-full pointer-events-none"></div>
          
          <div className="relative z-10">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-slate-100">
              <div className="flex items-center gap-4">
                <div className="bg-gradient-to-tr from-indigo-600 to-purple-600 p-2.5 rounded-xl shadow-md border border-indigo-400">
                   <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                   </svg>
                </div>
                <div>
                  <h2 className="text-2xl font-black text-slate-900 leading-tight">Projected Trajectory</h2>
                  <p className="text-sm font-bold text-indigo-600 uppercase tracking-widest mt-0.5">Algorithm Output Core</p>
                </div>
              </div>
              
              <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 px-3 py-1.5 rounded-lg text-xs font-bold text-slate-600">
                <span className="w-2.5 h-2.5 bg-emerald-500 rounded-sm"></span>
                HIGH CONFIDENCE
              </div>
            </div>
            
            <div className="text-slate-800 leading-relaxed text-lg sm:text-xl font-medium bg-white/60 backdrop-blur-sm p-6 rounded-2xl border border-white shadow-sm ring-1 ring-slate-900/5">
              {careerPathData.careerPath || "Empty tensor array payload generated."}
            </div>
            
            <div className="mt-10 bg-slate-50 border border-slate-200 p-6 rounded-2xl">
              <div className="flex items-center gap-2 mb-2 text-indigo-700">
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                   <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                 </svg>
                 <span className="font-black tracking-wide text-sm">PATH RATIONALE</span>
              </div>
              <p className="text-sm text-slate-600 leading-relaxed max-w-3xl">
                This projection is constructed dynamically by calculating the Euclidean distance between your current metadata embeddings (50% Skills, 30% XP, 20% Academic) and successful market archetypes stored within the PathFinder graph network.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
